language: go

script: make test

before_install:
    - git clone --single-branch --branch v0.54.0 -- https://github.com/gohugoio/hugo.git $GOPATH/github.com/gohugoio/hugo
    - cd $GOPATH/github.com/gohugoio/hugo
    - go install --tags extended
    - cd -

notifications:
    email: false
