#!/bin/sh -eu

BRANCH="gh-pages-test"

DIR=$(dirname "$0")

cd ${DIR}/hugo

if ! git diff-files --quiet ; then
 echo "git repo has unstaged changes"
 exit 1
fi

echo "Deleting old publication"
rm -rf public
mkdir public
git worktree prune
rm -rf .git/worktrees/public/

echo "Checking out ${BRANCH} branch into public"
git worktree add -B ${BRANCH} public origin/${BRANCH}

echo "Removing existing files"
rm -rf public/*

echo "Generating site"
hugo

echo "Updating ${BRANCH} branch"
cd public && git add --all && git commit -m "Publishing site to ${BRANCH}"

git push origin ${BRANCH}
